# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'YTDownloader.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(614, 450)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.title = QLabel(self.centralwidget)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(30, 10, 271, 41))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.title.setFont(font)
        self.dl_progress = QProgressBar(self.centralwidget)
        self.dl_progress.setObjectName(u"dl_progress")
        self.dl_progress.setGeometry(QRect(30, 410, 371, 23))
        self.dl_progress.setValue(24)
        self.dl_progress.setTextVisible(True)
        self.link_label = QLabel(self.centralwidget)
        self.link_label.setObjectName(u"link_label")
        self.link_label.setGeometry(QRect(30, 60, 71, 21))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(False)
        self.link_label.setFont(font1)
        self.link_text = QLineEdit(self.centralwidget)
        self.link_text.setObjectName(u"link_text")
        self.link_text.setGeometry(QRect(100, 60, 391, 22))
        self.dl_button = QPushButton(self.centralwidget)
        self.dl_button.setObjectName(u"dl_button")
        self.dl_button.setGeometry(QRect(490, 360, 91, 41))
        self.cb_res = QComboBox(self.centralwidget)
        self.cb_res.setObjectName(u"cb_res")
        self.cb_res.setGeometry(QRect(385, 370, 91, 22))
        self.save_label = QLabel(self.centralwidget)
        self.save_label.setObjectName(u"save_label")
        self.save_label.setGeometry(QRect(30, 370, 71, 21))
        font2 = QFont()
        font2.setPointSize(11)
        self.save_label.setFont(font2)
        self.path_text = QLineEdit(self.centralwidget)
        self.path_text.setObjectName(u"path_text")
        self.path_text.setGeometry(QRect(100, 370, 221, 22))
        self.find_button = QPushButton(self.centralwidget)
        self.find_button.setObjectName(u"find_button")
        self.find_button.setGeometry(QRect(510, 50, 75, 41))
        self.loc_button = QPushButton(self.centralwidget)
        self.loc_button.setObjectName(u"loc_button")
        self.loc_button.setGeometry(QRect(332, 370, 41, 24))
        self.nov_label = QLabel(self.centralwidget)
        self.nov_label.setObjectName(u"nov_label")
        self.nov_label.setGeometry(QRect(405, 223, 41, 21))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        self.nov_label.setFont(font3)
        self.durasi_label = QLabel(self.centralwidget)
        self.durasi_label.setObjectName(u"durasi_label")
        self.durasi_label.setGeometry(QRect(405, 253, 91, 21))
        self.durasi_label.setFont(font3)
        self.rating_label = QLabel(self.centralwidget)
        self.rating_label.setObjectName(u"rating_label")
        self.rating_label.setGeometry(QRect(405, 283, 71, 21))
        self.rating_label.setFont(font3)
        self.thumbnail_set = QLabel(self.centralwidget)
        self.thumbnail_set.setObjectName(u"thumbnail_set")
        self.thumbnail_set.setGeometry(QRect(38, 145, 341, 191))
        self.thumbnail_set.setAlignment(Qt.AlignCenter)
        self.pub_label = QLabel(self.centralwidget)
        self.pub_label.setObjectName(u"pub_label")
        self.pub_label.setGeometry(QRect(405, 173, 81, 21))
        self.pub_label.setFont(font3)
        self.pub_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.judul = QLabel(self.centralwidget)
        self.judul.setObjectName(u"judul")
        self.judul.setGeometry(QRect(30, 100, 551, 21))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(False)
        self.judul.setFont(font4)
        self.judul.setAlignment(Qt.AlignCenter)
        self.pub_date = QLabel(self.centralwidget)
        self.pub_date.setObjectName(u"pub_date")
        self.pub_date.setGeometry(QRect(405, 193, 171, 21))
        font5 = QFont()
        font5.setPointSize(10)
        self.pub_date.setFont(font5)
        self.view = QLabel(self.centralwidget)
        self.view.setObjectName(u"view")
        self.view.setGeometry(QRect(455, 223, 121, 21))
        self.view.setFont(font5)
        self.durasi = QLabel(self.centralwidget)
        self.durasi.setObjectName(u"durasi")
        self.durasi.setGeometry(QRect(505, 253, 71, 21))
        self.durasi.setFont(font5)
        self.peringkat = QLabel(self.centralwidget)
        self.peringkat.setObjectName(u"peringkat")
        self.peringkat.setGeometry(QRect(485, 283, 91, 21))
        self.peringkat.setFont(font5)
        self.author_label = QLabel(self.centralwidget)
        self.author_label.setObjectName(u"author_label")
        self.author_label.setGeometry(QRect(405, 143, 71, 16))
        self.author_label.setFont(font3)
        self.author = QLabel(self.centralwidget)
        self.author.setObjectName(u"author")
        self.author.setGeometry(QRect(470, 140, 111, 21))
        self.author.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.title.setText(QCoreApplication.translate("MainWindow", u"Youtube Downloader", None))
        self.link_label.setText(QCoreApplication.translate("MainWindow", u"Link:", None))
        self.dl_button.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.save_label.setText(QCoreApplication.translate("MainWindow", u"Save to:", None))
        self.find_button.setText(QCoreApplication.translate("MainWindow", u"Find", None))
        self.loc_button.setText(QCoreApplication.translate("MainWindow", u"Loc", None))
        self.nov_label.setText(QCoreApplication.translate("MainWindow", u"Views:", None))
        self.durasi_label.setText(QCoreApplication.translate("MainWindow", u"Durasi Video: ", None))
        self.rating_label.setText(QCoreApplication.translate("MainWindow", u"Peringkat:", None))
        self.thumbnail_set.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pub_label.setText(QCoreApplication.translate("MainWindow", u"Publish Date:", None))
        self.judul.setText("")
        self.pub_date.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.view.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.durasi.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.peringkat.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.author_label.setText(QCoreApplication.translate("MainWindow", u"Channel:", None))
        self.author.setText(QCoreApplication.translate("MainWindow", u"-", None))
    # retranslateUi

